name: Deploy to Vercel

# This workflow will run on push events to the main branch
on:
  push:
    branches:
      - main  # Triggers deployment when pushing to the main branch

# Define the jobs that will run in this workflow
jobs:
  deploy:
    runs-on: ubuntu-latest  # The environment for the job (Ubuntu in this case)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code from the GitHub repository

    - name: Set up Python environment
      uses: actions/setup-python@v2  # Set up a Python environment
      with:
        python-version: '3.9'  # The version of Python you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt      # Install all dependencies from requirements.txt

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install -g vercel  # Install Vercel CLI globally
        vercel --prod --token=$VERCEL_TOKEN --yes  # Deploy to production using the --yes flag
      

    - name: Notify deployment success
      run: echo "Deployment successful!"
